### ISSUE TITLE
Add ability to manipulate  `indexDB`

### ISSUE THREAD

**Issue by 108yen** [yamada-ui/yamada-theme#39]
### Subject

db

### Description

The next step in #38 and #37 is to add functionality to manipulate the `indexDB`.

- Function to get `theme`.
- Function to write `theme`.
- Function to get `theme` for a specific component.
- Function to write `theme` for a specific component.

### Are you willing to participate in the development of this feature and create a pull request?

None

**Comment by odendayoko** [comment]
## 関数の機能要件
- Function to get theme.
- Function to write theme.

themeを丸々indexedDBに保存できる + 取り出せる関数

### 用途の例
- AさんがBさんにthemeファイルを共有し、BさんがYamadaTheme内に取り込む

**Comment by odendayoko** [comment]
merged
